version: '3.8'
# sudo docker run -d -p 27017:27017 --restart=always -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=1234 --name scrum-poker-database --network scrum-poker -v data-db:/data/db mongo:latest
# sudo docker run -d -p 27017:27017 --name scrum-poker-database --network scrum-poker -v data-db:/data/db mongo:latest

services:
  database:
    image: mongo:latest
    restart: always
    container_name: scrum-poker-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scrum-poker-backend
    environment:
      - PORT=${PORT}
      - MONGODB_URL=mongodb://database:27017
    ports:
      - '3001:3001'
    depends_on:
      - database
