version: '3.8'

services:
  shift-intensive-database:
    image: mongo:latest
    restart: always
    container_name: shift-intensive-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27018:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  shift-intensive-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shift-intensive-service
    environment:
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm123456
      - PORT=${PORT}
      - DATABASE_URL=mongodb://shift-intensive-database:27017
    ports:
      - '3001:3001'
    depends_on:
      - shift-intensive-database
