version: '3.8'

services:
  shift-intensive-database:
    image: mongo:latest
    restart: always
    container_name: shift-intensive-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27018:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  shift-intensive-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shift-intensive-service
    environment:
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm123456
      - PORT=${PORT}
      - DATABASE_URL=mongodb://admin:1234@shift-intensive-database:27017
      - SERVER_URL=http://localhost:3001/
    ports:
      - '3001:3001'
    depends_on:
      - shift-intensive-database

  shift-intensive-sql:
    image: postgres:latest
    restart: always
    container_name: shift-intensive-sql
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pokemon
    volumes:
      - type: bind
        source: ./data
        target: /data/db
