version: '3.8'
# sudo docker run -d -p 27018:27017 --restart=always -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=1234 --name shift-intensive-database --network shift-intensive -v shift-intensive-data-db:/data/db mongo:latest
# sudo docker run -d -p 27018:27017 --name shift-intensive-database --network shift-intensive-poker -v data-db:/data/db mongo:latest

services:
  shift-intensive-database:
    image: mongo:latest
    restart: always
    container_name: shift-intensive-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  shift-intensive-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shift-intensive-service
    environment:
      - JWT_SECRET=qwertyuiopasdfghjklzxcvbnm123456
      - PORT=${PORT}
      - MONGODB_URL=mongodb://shift-intensive-database:27017
    ports:
      - '3001:3001'
    depends_on:
      - shift-intensive-database
