import { Car } from '../entities';
import { BodyType, Brand, Color, Transmission } from './enums';

export const cars: Car[] = [
  {
    id: '1',
    name: 'BMW X5',
    brand: Brand.BMW,
    imageUrl: 'https://example.com/bmw-x5.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 5000,
    location: 'Москва, ул. Тверская, 10',
    minRentalDays: 2,
    color: Color.BLACK,
    bodyType: BodyType.SUV,
    steering: 'left',
    available: true
  },
  {
    id: '2',
    name: 'Audi A6',
    brand: Brand.AUDI,
    imageUrl: 'https://example.com/audi-a6.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 4500,
    location: 'Санкт-Петербург, Невский пр., 20',
    minRentalDays: 3,
    color: Color.WHITE,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: true
  },
  {
    id: '3',
    name: 'Mercedes E-Class',
    brand: Brand.MERCEDES,
    imageUrl: 'https://example.com/mercedes-e.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 5500,
    location: 'Новосибирск, ул. Ленина, 5',
    minRentalDays: 1,
    color: Color.SILVER,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: false
  },
  {
    id: '4',
    name: 'BMW 3 Series',
    brand: Brand.BMW,
    imageUrl: 'https://example.com/bmw-3.jpg',
    transmission: Transmission.MANUAL,
    price: 3500,
    location: 'Екатеринбург, ул. Малышева, 15',
    minRentalDays: 2,
    color: Color.BLUE,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: true
  },
  {
    id: '5',
    name: 'Audi Q7',
    brand: Brand.AUDI,
    imageUrl: 'https://example.com/audi-q7.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 6000,
    location: 'Калининград, Ленинский пр., 30',
    minRentalDays: 2,
    color: Color.BLACK,
    bodyType: BodyType.SUV,
    steering: 'left',
    available: true
  },
  {
    id: '6',
    name: 'Mercedes GLE',
    brand: Brand.MERCEDES,
    imageUrl: 'https://example.com/mercedes-gle.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 6500,
    location: 'Уфа, ул. Революционная, 12',
    minRentalDays: 3,
    color: Color.WHITE,
    bodyType: BodyType.SUV,
    steering: 'left',
    available: true
  },
  {
    id: '7',
    name: 'BMW 5 Series',
    brand: Brand.BMW,
    imageUrl: 'https://example.com/bmw-5.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 4800,
    location: 'Ростов-на-Дону, ул. Большая Садовая, 25',
    minRentalDays: 1,
    color: Color.RED,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: false
  },
  {
    id: '8',
    name: 'Audi A4',
    brand: Brand.AUDI,
    imageUrl: 'https://example.com/audi-a4.jpg',
    transmission: Transmission.MANUAL,
    price: 3800,
    location: 'Алматы, ул. Абая, 50',
    minRentalDays: 2,
    color: Color.BLUE,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: true
  },
  {
    id: '9',
    name: 'Mercedes S-Class',
    brand: Brand.MERCEDES,
    imageUrl: 'https://example.com/mercedes-s.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 8000,
    location: 'Кишинёв, ул. Штефана чел Маре, 1',
    minRentalDays: 3,
    color: Color.BLACK,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: true
  },
  {
    id: '10',
    name: 'BMW 7 Series',
    brand: Brand.BMW,
    imageUrl: 'https://example.com/bmw-7.jpg',
    transmission: Transmission.AUTOMATIC,
    price: 7500,
    location: 'Душанбе, пр. Рудаки, 22',
    minRentalDays: 2,
    color: Color.SILVER,
    bodyType: BodyType.SEDAN,
    steering: 'left',
    available: true
  }
];
